"""empty message

Revision ID: 3451051754b4
Revises: febd3c13f6d1
Create Date: 2019-11-21 14:11:58.599088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3451051754b4'
down_revision = 'febd3c13f6d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.String(), nullable=True))
    op.add_column('user', sa.Column('city', sa.String(), nullable=True))
    op.add_column('user', sa.Column('cp', sa.String(), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(), nullable=True))
    op.add_column('user', sa.Column('firstName', sa.String(), nullable=True))
    op.add_column('user', sa.Column('lastName', sa.String(), nullable=True))
    op.add_column('user', sa.Column('state', sa.String(), nullable=True))
    op.drop_column('user', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'state')
    op.drop_column('user', 'lastName')
    op.drop_column('user', 'firstName')
    op.drop_column('user', 'email')
    op.drop_column('user', 'cp')
    op.drop_column('user', 'city')
    op.drop_column('user', 'address')
    # ### end Alembic commands ###
