"""empty message

Revision ID: 4946e70c43ce
Revises: d15b5238d986
Create Date: 2019-11-18 19:07:11.286070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4946e70c43ce'
down_revision = 'd15b5238d986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hhr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idPersona', sa.Integer(), nullable=True),
    sa.Column('heartRate', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idPersona', sa.Integer(), nullable=True),
    sa.Column('motionlessTime', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idPersona', sa.Integer(), nullable=True),
    sa.Column('currentHeartRate', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idPersona', sa.Integer(), nullable=True),
    sa.Column('stressLevel', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('historicMotionless')
    op.drop_table('heartRate')
    op.drop_table('historicStress')
    op.drop_table('historicHeartRate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historicHeartRate',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"historicHeartRate_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('idPersona', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('heartRate', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='historicHeartRate_pkey')
    )
    op.create_table('historicStress',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"historicStress_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('idPersona', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stressLevel', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='historicStress_pkey')
    )
    op.create_table('heartRate',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"heartRate_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('idPersona', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('currentHeartRate', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='heartRate_pkey')
    )
    op.create_table('historicMotionless',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"historicMotionless_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('idPersona', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('motionlessTime', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='historicMotionless_pkey')
    )
    op.drop_table('hs')
    op.drop_table('hr')
    op.drop_table('hm')
    op.drop_table('hhr')
    # ### end Alembic commands ###
