"""empty message

Revision ID: d15b5238d986
Revises: 7b703c45eeae
Create Date: 2019-11-18 17:07:40.784919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd15b5238d986'
down_revision = '7b703c45eeae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mood', sa.Column('happy', sa.String(), nullable=True))
    op.add_column('mood', sa.Column('neutro', sa.String(), nullable=True))
    op.add_column('mood', sa.Column('sad', sa.String(), nullable=True))
    op.drop_column('mood', 'date')
    op.drop_column('mood', 'mood')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mood', sa.Column('mood', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mood', sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('mood', 'sad')
    op.drop_column('mood', 'neutro')
    op.drop_column('mood', 'happy')
    # ### end Alembic commands ###
