"""empty message

Revision ID: febd3c13f6d1
Revises: 4946e70c43ce
Create Date: 2019-11-18 20:02:45.033259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'febd3c13f6d1'
down_revision = '4946e70c43ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motionless', sa.Column('currentMotionlessTime', sa.String(), nullable=True))
    op.drop_column('motionless', 'CurrentmotionlessTime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motionless', sa.Column('CurrentmotionlessTime', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('motionless', 'currentMotionlessTime')
    # ### end Alembic commands ###
